### PR TITLE
Support XEP-0184: Message Delivery Receipts

### PR DESCRIPTION
**Pull request by weiss**

### CODE REVIEW

**Comment by zinid** [comment]
We should use records in result, otherwise encoding won't work (there is no way to know how to encode `true` or `<<"id123">>`). But if we don't need encoding, then it's fine.

**Comment by zinid** [comment]
Also, XEP-0184 support should be mentioned in [README](https://github.com/processone/xmpp#supported-xmpp-elements).

**Comment by weiss** [comment]
> We should use records in result, otherwise encoding won't work (there is no way to know how to encode `true` or `<<"id123">>`). But if we don't need encoding, then it's fine.

Well I don't need encoding :smile:

I've seen you using `true` in many places and wasn't sure about the policy, but now I realized that you maybe used it only for elements that are just `#ref`erenced from other elements?

> Also, XEP-0184 support should be mentioned in [README](https://github.com/processone/xmpp#supported-xmpp-elements).

Ah I keep forgetting that, sorry.

I force-pushed an update to fix these things.

**Comment by zinid** [comment]
Excellent
Thanks a lot

**Pull request merged**
